### ISSUE TITLE
meta.yaml should pin icu 58.*

### ISSUE THREAD

**Issue by trey-stafford** [conda-forge/fiona-feedstock#37]
Installing fiona with other dependencies requiring the `icu` package at a version less than 58 will allow fiona to be installed without failure. However, attempting to import fiona results in the following errror:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.5/site-packages/fiona/__init__.py", line 69, in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
  File "/opt/conda/lib/python3.5/site-packages/fiona/collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: libicui18n.so.58: cannot open shared object file: No such file or directory
```

Adding `- icu 58.*` to fiona's dependency list in the `meta.yaml` should resolve this issue by preventing such incompatible package installations from occurring.

**Comment by ocefpaf** [comment]
> Installing fiona with other dependencies requiring the icu package at a version less than 58 will allow fiona to be installed without failure. 

That shoudl happen only if you are using an older conda or conda-forge is not at the top of your channel preference. We do not recommend over-specifying dependencies just to fix that because it will lead to confusion and inflated recipes.

Please take a look at https://github.com/conda-forge/conda-forge.github.io/pull/325 for more info.
